MAXIMUM_EPOCHS = 1000
EARLY_STOP_EPOCHS = 15
LEARNING_RATE_EPOCHS = 5
OPTIMIZER_DIRECTION = 'minimize'
RESULTS_DIRECTORY = 'output/'
IMAGE_PATH = '~/Documents/Research/VISAGE_a/DeepUAge_dataset'
IMAGE_SIZE = 224
LOG_RESULTS = False

